# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - BioMedicalApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install, build, and test
        run: |
          npm install -g @angular/cli
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist/bio-medical-cloud

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "BioMedicalApp"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_83cea9d0d3f74fabbda5abf3d74070ff }}
          package: .
  
  ACR:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      name: Build the Container image
      id: bci
      uses: actions/checkout@v2
      uses: azure/docker-login@v1
      with:
        login-server: biomedicalapp.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t biomedicalapp.azurecr.io/myapp:${{ github.sha }}
        docker push biomedicalapp.azurecr.io/myapp:${{ github.sha }}     
